package tools

func OutputSchema(name string) map[string]any {
	props := map[string]any{}
	// MCP envelope 的 isError 已表达工具调用错误；这里只描述领域结果，
	// 不再要求含义模糊的通用 ok 字段。
	required := []string{}
	stringProp := func(desc string) map[string]any { return map[string]any{"type": "string", "description": desc} }
	intProp := func(desc string) map[string]any { return map[string]any{"type": "integer", "description": desc} }
	boolProp := func(desc string) map[string]any { return map[string]any{"type": "boolean", "description": desc} }
	arrayProp := func(desc string) map[string]any {
		return map[string]any{"type": "array", "description": desc, "items": map[string]any{"type": "object", "additionalProperties": true}}
	}
	objectProp := func(desc string) map[string]any {
		return map[string]any{"type": "object", "description": desc, "additionalProperties": true}
	}

	switch name {
	case "server_info":
		props["server"] = stringProp("Server identifier.")
		props["title"] = stringProp("Human-readable server title.")
		props["version"] = stringProp("Server version.")
		props["workspace"] = stringProp("AgentDock default directory.")
		props["default_cwd"] = stringProp("Default cwd relative to ~/AgentDock when applicable.")
		props["tools"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		props["tool_count"] = intProp("Number of exposed tools.")
		props["task_state_dir"] = stringProp("Local directory containing persistent recoverable task state.")
		props["workflow_dir"] = stringProp("Local directory containing workflow templates.")
		props["sandbox"] = objectProp("Sandbox status metadata.")
	case "agentdock_context":
		required = []string{"context"}
		props["context"] = stringProp("Rendered AgentDock bootstrap context text for clients that cannot inject system prompt context.")
	case "read_file":
		props["path"] = stringProp("Host path or skill:// resource URI. Relative Host paths resolve from ~/AgentDock.")
		props["content"] = stringProp("Text content slice.")
		props["encoding"] = stringProp("Detected text encoding.")
		props["size_bytes"] = intProp("File size in bytes.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["truncated_reason"] = stringProp("Reason output was truncated.")
		props["start_line"] = intProp("Returned start line.")
		props["end_line"] = intProp("Returned end line.")
		props["next_start_line"] = intProp("Next line to read when output was truncated.")
		props["total_lines"] = intProp("Total line count.")
	case "list_dir":
		props["path"] = stringProp("Host directory path. Relative paths resolve from ~/AgentDock.")
		props["entries"] = arrayProp("Directory entries.")
		props["truncated"] = boolProp("Whether entries were truncated.")
	case "list_files":
		props["path"] = stringProp("Host directory path. Relative paths resolve from ~/AgentDock.")
		props["files"] = arrayProp("Matched files.")
		props["truncated"] = boolProp("Whether files were truncated.")
	case "search_text":
		props["matches"] = arrayProp("Text search matches.")
		props["engine"] = stringProp("Search engine used: rg or go_fallback.")
		props["truncated"] = boolProp("Whether matches were truncated.")
	case "file_edit":
		props["action"] = stringProp("File edit action.")
		props["summary"] = stringProp("Result summary.")
		props["path"] = stringProp("Host path. Relative paths resolve from ~/AgentDock.")
		props["dry_run"] = boolProp("Whether this was a dry run.")
		props["matches"] = intProp("Match count for replace.")
		props["changed"] = boolProp("Whether content changed.")
		props["diff_preview"] = stringProp("Diff preview.")
		props["files_changed"] = intProp("Changed file count.")
		props["insertions"] = intProp("Inserted line count.")
		props["deletions"] = intProp("Deleted line count.")

	case "exec_command", "session_observe", "session_act":
		props["session_id"] = stringProp("Command session id.")
		props["status"] = stringProp("Session status.")
		props["runtime"] = stringProp("Command runtime when reported by the host, such as windows or wsl.")
		props["wsl_distribution"] = stringProp("WSL distribution selected for the command when explicitly configured.")
		props["workdir"] = stringProp("Logical command working directory in the selected runtime.")
		props["stdout"] = stringProp("Captured stdout segment.")
		props["stderr"] = stringProp("Captured stderr segment.")
		props["command_ok"] = boolProp("Whether a completed command exited successfully. Omitted while the command is still running.")
		props["command_error"] = stringProp("Command process error when execution did not succeed.")
		props["exit_code"] = intProp("Process exit code, when available.")
		props["elapsed_ms"] = intProp("Session elapsed milliseconds.")
		props["timed_out"] = boolProp("Whether the command timed out.")
		props["diagnostic"] = objectProp("Structured diagnostic for common failures.")
		if name == "exec_command" {
			props["session_reason"] = stringProp("Why exec_command returned a session instead of a completed result.")
			props["observe_after_ms"] = intProp("Suggested delay before inspecting the returned session.")
		}
	case "task_manage":
		props["action"] = stringProp("Completed task action.")
		props["task_id"] = stringProp("Persistent task id returned by create and usable with task lifecycle actions.")
		props["task"] = objectProp("Full persistent task state returned only by get.")
		props["task_summary"] = objectProp("Compact task summary returned by task lifecycle actions.")
		props["next_required_action"] = stringProp("Concise guidance for checkpoint progress, template composition, or final review.")
		props["review_status"] = stringProp("Final review status when present: not_started, pass, or failed.")
		props["final_review"] = objectProp("Compact final review state with status and counts.")
		props["tasks"] = arrayProp("Compact task summaries ordered by most recent update.")
		props["count"] = intProp("Returned item count.")
		props["state_dir"] = stringProp("Local AgentDock task state directory.")
	case "workflow_template_manage":
		props["action"] = stringProp("Completed workflow template action.")
		props["template"] = objectProp("Full workflow template returned by get.")
		props["templates"] = arrayProp("Compact summaries from list or full active templates from get_many.")
		props["composition_required"] = boolProp("Whether the returned templates must be combined by the model before task creation.")
		props["next_required_action"] = stringProp("Required model action after get_many.")
		props["template_id"] = stringProp("Workflow template id returned by save, validate, publish, or retire.")
		props["template_summary"] = objectProp("Compact workflow template summary returned by save, validate, publish, retire, and list items.")
		props["valid"] = boolProp("Whether a draft workflow template passed validation.")
		props["count"] = intProp("Returned item count.")
		props["workflow_dir"] = stringProp("Local AgentDock workflow template directory.")
		props["candidates"] = arrayProp("Matched workflow template candidates with scores and reasons.")
		props["vector_search_enabled"] = boolProp("Whether optional embedding-backed template vector search is enabled for match.")
		props["vector_index_status"] = stringProp("Template vector index status: disabled, ready, or degraded.")
		props["vector_index_items"] = intProp("Number of persisted template vectors for the current embedding model.")
		props["vector_index_available"] = boolProp("Whether workflow vector index content is available for export.")
		props["content"] = stringProp("Raw workflow vector index JSON returned by vector_index.")
		props["embedding_model"] = stringProp("Embedding model configured for template vector search.")
		props["recommended"] = stringProp("Template recommendation: use_template, consider_template, or plain_task.")
		props["recommendation_reason"] = stringProp("Reason for recommendation.")
		props["best_candidate_score"] = intProp("Highest template match score.")
		props["score_thresholds"] = objectProp("Template match score thresholds.")

	case "skill_package":
		props["action"] = stringProp("Completed Skill package action.")
		props["skill"] = stringProp("Skill name.")
		props["name"] = stringProp("Skill name for environment actions.")
		props["key"] = stringProp("Environment variable name. Secret values are never returned.")
		props["configured"] = boolProp("Whether the environment variable has a non-empty configured value.")
		props["removed"] = boolProp("Whether the environment variable was removed.")
		props["items"] = arrayProp("Environment variable names and configured status without values.")
		props["count"] = intProp("Returned environment variable count.")
		props["valid"] = boolProp("Whether a Skill source passed validation.")
		props["source"] = stringProp("Resolved Skill source label.")
		props["digest"] = stringProp("Computed Skill package digest.")
		props["issues"] = arrayProp("Structured validation issues.")
		props["document"] = objectProp("Parsed SKILL.md frontmatter and body metadata.")
		props["result"] = objectProp("Install, activate, or rollback result.")
	case "mcp_manage":
		props["action"] = stringProp("Completed dynamic MCP management action.")
		props["servers"] = arrayProp("Registered dynamic MCP server summaries.")
		props["server"] = objectProp("Dynamic MCP server summary.")
		props["config"] = objectProp("Dynamic MCP server configuration containing only non-secret values and environment variable names.")
		props["tools"] = arrayProp("Discovered lightweight MCP tool summaries.")
		props["tool_count"] = intProp("Discovered tool count.")
		props["count"] = intProp("Registered server count.")
		props["name"] = stringProp("Dynamic MCP server name.")
		props["removed"] = boolProp("Whether the server or environment variable was removed.")
		props["key"] = stringProp("Environment variable name. Secret values are never returned.")
		props["configured"] = boolProp("Whether the environment variable has a non-empty configured value.")
		props["items"] = arrayProp("Environment variable names and configured status without values.")
	case "mcp_tool_search":
		props["query"] = stringProp("Capability query used.")
		props["server"] = stringProp("Optional server filter used.")
		props["tools"] = arrayProp("Matching lightweight MCP tool summaries.")
		props["count"] = intProp("Matching tool count.")
	case "mcp_tool_inspect":
		props["name"] = stringProp("Qualified MCP tool name.")
		props["server"] = stringProp("Dynamic MCP server name.")
		props["tool_name"] = stringProp("Upstream MCP tool name.")
		props["title"] = stringProp("Tool title.")
		props["description"] = stringProp("Tool description.")
		props["input_schema"] = objectProp("Complete upstream MCP tool input schema.")
		props["output_schema"] = objectProp("Optional upstream MCP tool output schema.")
		props["annotations"] = objectProp("Optional upstream MCP tool annotations.")
	case "mcp_tool_call":
		props["name"] = stringProp("Qualified MCP tool name.")
		props["result"] = objectProp("Raw upstream MCP tools/call result, including content and structuredContent when supplied.")
	case "file_publish":
		props["artifact_id"] = stringProp("Published artifact id.")
		props["url"] = stringProp("Optional temporary signed download URL when a reachable base URL is available.")
		props["expires_at"] = stringProp("Signed URL expiry timestamp.")
		props["sha256"] = stringProp("Snapshot payload SHA-256.")
		props["size_bytes"] = intProp("Snapshot payload size in bytes.")
		props["mime_type"] = stringProp("Payload media type.")
		props["filename"] = stringProp("Download filename used for Content-Disposition and signature verification.")
		props["archive"] = boolProp("Whether the source directory was packaged as tar.gz.")
		props["width"] = intProp("Image width when the payload is an image.")
		props["height"] = intProp("Image height when the payload is an image.")
	case "recall_bootstrap":
		props["recall_endpoint"] = stringProp("Configured NexusDock Recall endpoint.")
		props["project"] = stringProp("Backend-selected NexusDock Recall context returned by the backing service; not an input selector for the model.")
		props["sections"] = arrayProp("Packed recall sections. Raw Markdown is omitted by default and returned as raw_content only when include_raw=true.")
		props["count"] = intProp("Section count.")
		props["bytes"] = intProp("Combined bytes.")
	case "recall_search":
		props["recall_endpoint"] = stringProp("Configured NexusDock Recall endpoint.")
		props["recall_kind"] = stringProp("Search kind used.")
		props["query"] = stringProp("Search query.")
		props["results"] = arrayProp("Search results.")
		props["candidate_paths"] = arrayProp("Candidate note paths when kind=note.")
		props["candidates"] = arrayProp("Scored candidate notes when kind=note.")
		props["search_result_count"] = intProp("Raw result count before compaction when kind=note.")
		props["search_results"] = arrayProp("Raw search results when requested.")
		props["count"] = intProp("Search result count.")
	case "recall_read":
		props["recall_endpoint"] = stringProp("Configured NexusDock Recall endpoint.")
		props["recall"] = objectProp("NexusDock Recall document returned by the backing service. Raw Markdown is omitted by default and returned as raw_content only when include_raw=true.")
	case "recall_write":
		props["recall_endpoint"] = stringProp("Configured NexusDock Recall endpoint.")
		props["recall_target"] = stringProp("Recall target used.")
		props["recall_action"] = stringProp("Recall action used.")
		props["recall"] = objectProp("NexusDock Recall document returned by the backing service when a write occurs.")
		props["card"] = objectProp("Normalized card candidate or written card when target=card.")
		props["warnings"] = arrayProp("Review warnings before writing.")
		props["capture_plan"] = objectProp("Reviewable write plan for card or note captures.")
		props["similar_results"] = arrayProp("Similar existing card search results.")
		props["path"] = stringProp("NexusDock Recall-relative path.")
		props["changed"] = boolProp("Whether the proposed edit changes content.")
		props["dry_run"] = boolProp("Whether the operation only previewed changes.")
		props["confirmed"] = boolProp("Whether write confirmation was supplied.")
		props["written"] = boolProp("Whether the entry was written.")
		props["diff"] = stringProp("Unified diff preview.")
		props["updates"] = arrayProp("Fact update results.")
	case "recall_maintain":
		props["recall_endpoint"] = stringProp("Configured NexusDock Recall endpoint.")
		props["recall_action"] = stringProp("Maintenance action performed.")
		props["entries"] = arrayProp("NexusDock Recall entries for action=list.")
		props["count"] = intProp("Entry count where applicable.")
		props["terms"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		props["files_scanned"] = intProp("Files scanned for action=lint.")
		props["finding_count"] = intProp("Finding count for action=lint.")
		props["findings"] = arrayProp("Lint findings.")
		props["git_repo"] = boolProp("Whether the NexusDock Recall store is a Git repository for action=sync_status.")
		props["auto_sync_enabled"] = boolProp("Whether NexusDock Recall auto sync is enabled.")
		props["pending_push"] = boolProp("Whether NexusDock Recall has remote sync work.")
		props["conflict"] = boolProp("Whether NexusDock Recall detected a sync conflict.")
	case "private_note_manage":
		props["root"] = stringProp("NexusDock private notes root path.")
		props["private_note_store"] = stringProp("Private note store name, fixed to NexusDock Private Notes.")
		props["action"] = stringProp("Action performed.")
		props["query"] = stringProp("Metadata-only query for action=search.")
		props["results"] = arrayProp("Metadata-only search results containing title, summary, tags, category, path, updated_at, and secret marker; never plaintext snippets.")
		props["metadata_only"] = boolProp("Whether search was restricted to safe metadata.")
		props["path"] = stringProp("Plain note path for read/write/delete results.")
		props["encrypted_path"] = stringProp("Age encrypted backup path, typically encrypted/<category>/<name>.md.age.")
		props["content"] = stringProp("Plaintext content returned only by explicit action=read.")
		props["truncated"] = boolProp("Whether returned content was truncated.")
		props["contains_secret"] = boolProp("Whether the note content is marked as containing secrets.")
		props["written"] = boolProp("Whether plaintext was written.")
		props["encrypted"] = boolProp("Whether encrypted backup was written.")
		props["deleted_plaintext"] = boolProp("Whether plaintext was deleted.")
		props["deleted_encrypted"] = boolProp("Whether encrypted backup was deleted.")
		props["notes"] = arrayProp("Metadata-only private note summaries for action=status status_action=list.")
		props["count"] = intProp("Result or note count.")
		props["notes_count"] = intProp("Private note count for status checks.")
		props["encrypted_count"] = intProp("Encrypted backup count for maintenance actions.")
		props["recipient"] = stringProp("Age public recipient generated or used.")
		props["identity_created"] = boolProp("Whether a new local age identity was created.")
		props["algorithm"] = stringProp("Encryption algorithm.")
		props["missing_encrypted"] = arrayProp("Missing encrypted backup paths.")
		props["encrypted_backup_ok"] = boolProp("Whether every private note has its required encrypted backup.")
		props["plaintext_git_ignored"] = boolProp("Whether private note plaintext is Git-ignored.")
		props["keys_git_ignored"] = boolProp("Whether private note keys are Git-ignored.")
	case "browser_session":
		props["browser_ok"] = boolProp("Whether the browser operation succeeded.")
		props["browser_error"] = stringProp("Browser operation error when the runner completed without a successful browser result.")
		props["error"] = objectProp("Structured browser error with code, message, phase, and optional details.")
		props["code"] = stringProp("Structured browser error code, such as PLAYWRIGHT_CHROMIUM_MISSING.")
		props["suggested_retry"] = objectProp("Structured retry suggestion for recoverable browser errors.")
		props["operation"] = stringProp("Browser operation name.")
		props["session_id"] = stringProp("Browser session id.")
		props["page_id"] = stringProp("Active browser page id when a page is already available.")
		props["pages"] = arrayProp("Browser pages available in the underlying session context.")
		props["status"] = stringProp("Browser session status.")
		props["profile_id"] = stringProp("Persistent browser profile id when a session uses profile_id.")
		props["removed_count"] = intProp("Number of stale browser sessions removed by cleanup.")
		props["removed_sessions"] = arrayProp("Browser session ids removed by cleanup.")
		props["stdout"] = stringProp("Raw browser runner output.")
		props["stderr"] = stringProp("Browser runner diagnostic stderr, kept separate from the JSON protocol stdout.")
	case "browser_act", "browser_snapshot":
		props["browser_ok"] = boolProp("Whether the browser operation succeeded.")
		props["browser_error"] = stringProp("Browser operation error when the runner completed without a successful browser result.")
		props["error"] = objectProp("Structured browser error with code, message, phase, and optional details.")
		props["code"] = stringProp("Structured browser error code, such as PLAYWRIGHT_CHROMIUM_MISSING.")
		props["suggested_retry"] = objectProp("Structured retry suggestion for recoverable browser errors.")
		props["browser_launch"] = objectProp("Browser launch metadata, including fallback details when system Chrome is used.")
		props["operation"] = stringProp("Browser operation name.")
		props["session_id"] = stringProp("Browser session id.")
		props["page_id"] = stringProp("Active browser page id.")
		props["pages"] = arrayProp("Browser pages available in the underlying session context.")
		props["url"] = stringProp("Current page URL.")
		props["title"] = stringProp("Current page title.")
		props["text"] = stringProp("Current page body text excerpt.")
		props["screenshot"] = objectProp("Artifact reference for the captured screenshot. Always includes artifact_id and includes url when a reachable base URL is available.")
		props["viewport"] = objectProp("Browser viewport size.")
		props["page_size"] = objectProp("Page scroll size and device pixel ratio.")
		props["focused_element"] = objectProp("Current focused element summary.")
		props["interactive_elements"] = arrayProp("Visible interactive elements summary.")
		props["screenshot_size_bytes"] = intProp("Screenshot file size in bytes.")
		props["screenshot_width"] = intProp("Estimated screenshot width.")
		props["screenshot_height"] = intProp("Estimated screenshot height.")
		props["closed"] = boolProp("Whether the session was closed by close_after.")
		props["storage_state_path"] = stringProp("Saved Playwright storage state path when requested.")
		props["console_errors"] = arrayProp("Browser console errors captured during the operation.")
		props["network_errors"] = arrayProp("Network request failures captured during the operation.")
		props["page_errors"] = arrayProp("Browser page runtime errors captured during the operation.")
		props["stdout"] = stringProp("Raw browser runner output.")
		props["stderr"] = stringProp("Browser runner diagnostic stderr, kept separate from the JSON protocol stdout.")
		props["truncated"] = boolProp("Whether output was truncated.")
	case "git_read":
		props["action"] = stringProp("Read action performed.")
		props["command"] = stringProp("Executed git command.")
		props["output"] = stringProp("Raw git output.")
		props["repo_path"] = stringProp("Repository path, when applicable.")
		props["repos"] = arrayProp("Repositories for action=repos.")
		props["count"] = intProp("Repository count for action=repos.")
		props["branch"] = stringProp("Branch status line.")
		props["upstream"] = stringProp("Upstream branch, when configured.")
		props["ahead"] = intProp("Commits ahead of upstream.")
		props["behind"] = intProp("Commits behind upstream.")
		props["files"] = arrayProp("Changed files or diff files.")
		props["clean"] = boolProp("Whether the worktree is clean.")
		props["commits"] = arrayProp("Parsed commits for action=log.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["diagnostic"] = objectProp("Structured diagnostic.")
		props["command_ok"] = boolProp("Whether the underlying Git command exited successfully, when a command was executed.")
		props["command_error"] = stringProp("Underlying Git command process error, when present.")
		props["credential_found"] = boolProp("Whether a stored GitHub credential was found for action=github_repo_access.")
		props["username"] = stringProp("Stored GitHub username for action=github_repo_access.")
		props["repo"] = stringProp("Checked repository for action=github_repo_access.")
		props["auth_status"] = intProp("GitHub API auth HTTP status for action=github_repo_access.")
		props["auth_login"] = stringProp("Authenticated GitHub login for action=github_repo_access.")
		props["repo_status"] = intProp("GitHub API repo HTTP status for action=github_repo_access.")
		props["repo_access"] = boolProp("Whether the repository is visible to the token for action=github_repo_access.")
	case "git_write":
		props["action"] = stringProp("Write action performed.")
		props["command"] = stringProp("Executed git command.")
		props["output"] = stringProp("Raw git output.")
		props["repo_path"] = stringProp("Repository path, when applicable.")
		props["dest"] = stringProp("Clone destination, when applicable.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["diagnostic"] = objectProp("Structured diagnostic.")
		props["command_ok"] = boolProp("Whether the underlying Git command exited successfully.")
		props["command_error"] = stringProp("Underlying Git command process error, when present.")
		props["push_succeeded"] = boolProp("Whether push exited successfully.")
		props["remote_updated"] = boolProp("Whether push changed remote refs.")
		props["up_to_date"] = boolProp("Whether push reported up-to-date.")
		props["warnings"] = arrayProp("Git warning lines.")
		props["fatal_but_non_blocking"] = boolProp("Whether fatal text was non-blocking.")
		props["push_status"] = stringProp("Structured push status.")
	case "view_image":
		props["source"] = objectProp("Resolved artifact, path, or URL source metadata.")
		props["image"] = objectProp("Processed image metadata attached as standard MCP image content.")
		props["original"] = objectProp("Original/crop metadata.")
		props["resized"] = boolProp("Whether image bytes changed due to crop/resize/re-encode.")
		props["warnings"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
	}

	switch name {
	case "read_file", "list_dir", "list_files", "search_text", "file_edit":
		addFileRuntimeOutputProperties(props)
	}
	return map[string]any{"type": "object", "properties": props, "required": required, "additionalProperties": true}
}
