package tools

func OutputSchema(name string) map[string]any {
	props := map[string]any{}
	required := []string{"ok"}
	stringProp := func(desc string) map[string]any { return map[string]any{"type": "string", "description": desc} }
	intProp := func(desc string) map[string]any { return map[string]any{"type": "integer", "description": desc} }
	floatProp := func(desc string) map[string]any { return map[string]any{"type": "number", "description": desc} }
	boolProp := func(desc string) map[string]any { return map[string]any{"type": "boolean", "description": desc} }
	arrayProp := func(desc string) map[string]any {
		return map[string]any{"type": "array", "description": desc, "items": map[string]any{"type": "object", "additionalProperties": true}}
	}
	objectProp := func(desc string) map[string]any {
		return map[string]any{"type": "object", "description": desc, "additionalProperties": true}
	}

	props["ok"] = boolProp("Whether the tool call completed successfully.")

	switch name {
	case "server_info":
		props["server"] = stringProp("Server identifier.")
		props["title"] = stringProp("Human-readable server title.")
		props["version"] = stringProp("Server version.")
		props["workspace"] = stringProp("Workspace root path.")
		props["default_cwd"] = stringProp("Default workspace-relative cwd.")
		props["tools"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		props["tool_count"] = intProp("Number of exposed tools.")
		props["task_state_dir"] = stringProp("Local directory containing persistent recoverable task state.")
		props["workflow_dir"] = stringProp("Local directory containing workflow templates.")
		props["sandbox"] = objectProp("Sandbox status metadata.")
	case "read_file":
		props["path"] = stringProp("Workspace-relative file path.")
		props["content"] = stringProp("Text content slice.")
		props["encoding"] = stringProp("Detected text encoding.")
		props["size_bytes"] = intProp("File size in bytes.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["truncated_reason"] = stringProp("Reason output was truncated.")
		props["start_line"] = intProp("Returned start line.")
		props["end_line"] = intProp("Returned end line.")
		props["next_start_line"] = intProp("Next line to read when output was truncated.")
		props["total_lines"] = intProp("Total line count.")
	case "list_dir":
		props["path"] = stringProp("Workspace-relative directory path.")
		props["entries"] = arrayProp("Directory entries.")
		props["truncated"] = boolProp("Whether entries were truncated.")
	case "list_files":
		props["path"] = stringProp("Workspace-relative directory path.")
		props["files"] = arrayProp("Matched files.")
		props["truncated"] = boolProp("Whether files were truncated.")
	case "search_text":
		props["matches"] = arrayProp("Text search matches.")
		props["engine"] = stringProp("Search engine used: rg or go_fallback.")
		props["truncated"] = boolProp("Whether matches were truncated.")
	case "workspace_edit":
		props["action"] = stringProp("Workspace edit action.")
		props["summary"] = stringProp("Result summary.")
		props["path"] = stringProp("Workspace-relative file path.")
		props["dry_run"] = boolProp("Whether this was a dry run.")
		props["matches"] = intProp("Match count for replace.")
		props["changed"] = boolProp("Whether content changed.")
		props["diff_preview"] = stringProp("Diff preview.")
		props["files_changed"] = intProp("Changed file count.")
		props["insertions"] = intProp("Inserted line count.")
		props["deletions"] = intProp("Deleted line count.")

	case "exec_command", "session_observe", "session_act":
		props["session_id"] = stringProp("Command session id.")
		props["status"] = stringProp("Session status.")
		props["stdout"] = stringProp("Captured stdout segment.")
		props["stderr"] = stringProp("Captured stderr segment.")
		props["exit_code"] = intProp("Process exit code, when available.")
		props["elapsed_ms"] = intProp("Session elapsed milliseconds.")
		props["timed_out"] = boolProp("Whether the command timed out.")
		props["diagnostic"] = objectProp("Structured diagnostic for common failures.")
	case "check_github_repo_access":
		props["credential_found"] = boolProp("Whether a stored GitHub credential was found.")
		props["username"] = stringProp("Stored GitHub username.")
		props["repo"] = stringProp("Checked repository.")
		props["auth_status"] = intProp("GitHub API auth HTTP status.")
		props["auth_login"] = stringProp("Authenticated GitHub login.")
		props["repo_status"] = intProp("GitHub API repo HTTP status.")
		props["repo_access"] = boolProp("Whether the repository is visible to the token.")
		props["diagnostic"] = objectProp("Structured access diagnostic.")
	case "task_manage":
		props["action"] = stringProp("Completed task action.")
		props["task_id"] = stringProp("Persistent task id returned by create and usable with get, final_review, or complete_after_review.")
		props["task"] = objectProp("Full persistent task state returned only by get.")
		props["task_summary"] = objectProp("Compact task summary returned by task lifecycle actions.")
		props["next_required_action"] = stringProp("Concise guidance for the next real non-task action or final review.")
		props["review_status"] = stringProp("Final review status when present: not_started, pass, or failed.")
		props["final_review"] = objectProp("Compact final review state with status and counts.")
		props["tasks"] = arrayProp("Compact task summaries ordered by most recent update.")
		props["count"] = intProp("Returned item count.")
		props["state_dir"] = stringProp("Local AgentDock task state directory.")
	case "workflow_template_manage":
		props["action"] = stringProp("Completed workflow template action.")
		props["template"] = objectProp("Full workflow template returned by get.")
		props["templates"] = arrayProp("Compact workflow template summaries returned by list.")
		props["template_id"] = stringProp("Workflow template id returned by save, validate, publish, or retire.")
		props["template_summary"] = objectProp("Compact workflow template summary returned by save, validate, publish, retire, and list items.")
		props["valid"] = boolProp("Whether a draft workflow template passed validation.")
		props["count"] = intProp("Returned item count.")
		props["workflow_dir"] = stringProp("Local AgentDock workflow template directory.")
		props["candidates"] = arrayProp("Matched workflow template candidates with scores and reasons.")
		props["vector_search_enabled"] = boolProp("Whether optional embedding-backed template vector search is enabled for match.")
		props["vector_index_status"] = stringProp("Template vector index status: disabled, ready, or degraded.")
		props["vector_index_items"] = intProp("Number of persisted template vectors for the current embedding model.")
		props["embedding_model"] = stringProp("Embedding model configured for template vector search.")
		props["recommended"] = stringProp("Template recommendation: use_template, consider_template, or plain_task.")
		props["recommendation_reason"] = stringProp("Reason for recommendation.")
		props["best_candidate_score"] = intProp("Highest template match score.")
		props["score_thresholds"] = objectProp("Template match score thresholds.")

	case "skill_manage":
		props["action"] = stringProp("Completed Skill action.")
		props["skill"] = stringProp("Skill name.")
		props["version"] = stringProp("Selected Skill version.")
		props["skills"] = arrayProp("Installed Skill summaries.")
		props["count"] = intProp("Installed Skill count.")
		props["versions"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}, "description": "Installed versions."}
		props["selection"] = objectProp("Active version, channels, and history.")
		props["manifest"] = objectProp("Parsed agentdock.yaml manifest.")
		props["binding_configured"] = boolProp("Whether a binding file exists for the Skill.")
		props["valid"] = boolProp("Whether a Skill source passed validation.")
		props["source"] = stringProp("Resolved Skill source label.")
		props["digest"] = stringProp("Computed Skill package digest.")
		props["env"] = arrayProp("Manifest and compat env declarations without values.")
		props["commands"] = arrayProp("Declared command dependency checks.")
		props["issues"] = arrayProp("Structured validation issues.")
		props["requires_no_env_confirm"] = boolProp("Whether confirmed_no_env is needed for a Skill with no env declarations.")
		props["result"] = objectProp("Install, run, or rollback result.")
	case "artifact_fetch_create", "artifact_fetch_status":
		props["fetch"] = objectProp("Artifact fetch metadata without local private keys or download tokens.")
	case "artifact_fetch_download":
		props["fetch_id"] = stringProp("Artifact fetch id.")
		props["status"] = stringProp("Artifact fetch status.")
		props["file_path"] = stringProp("Local output path marked for Connector file-result rewriting.")
		props["file_name"] = stringProp("Output filename.")
		props["mime_type"] = stringProp("Output media type.")
		props["size"] = intProp("Plaintext output size.")
		props["sha256"] = stringProp("Plaintext SHA-256.")
		props["resource_uri"] = stringProp("Short-lived HTTPS resource URI for MCP resource_link output.")
		props["output_expires_at"] = stringProp("Resource expiry timestamp.")
		props["mounted"] = boolProp("Whether mount confirmation and cleanup completed.")
	case "artifact_send":
		props["artifact"] = objectProp("Nexus artifact metadata without upload credentials or encryption keys.")
		props["deliveries"] = arrayProp("Per-device delivery status without delivery tokens or wrapped keys.")
		props["source"] = stringProp("Transferred source filename.")
		props["archive"] = boolProp("Whether a directory was packed as tar.gz.")
		props["encrypted"] = boolProp("Whether the uploaded payload was end-to-end encrypted.")
	case "env_manage":
		props["action"] = stringProp("Completed Env action.")
		props["skill"] = stringProp("Skill name.")
		props["skills"] = arrayProp("Skill env summaries.")
		props["vars"] = arrayProp("Redacted env entries.")
		props["var"] = objectProp("Redacted env entry.")
		props["count"] = intProp("Env item count.")
		props["deleted"] = boolProp("Whether a variable was deleted.")
		props["result"] = objectProp("Migration or verification result.")
		props["message"] = stringProp("Verification message.")
	case "recall_bootstrap":
		props["recall_endpoint"] = stringProp("Configured RecallDock endpoint.")
		props["project"] = stringProp("Backend-selected RecallDock context returned by the backing service; not an input selector for the model.")
		props["sections"] = arrayProp("Packed recall sections. Raw Markdown is omitted by default and returned as raw_content only when include_raw=true.")
		props["count"] = intProp("Section count.")
		props["bytes"] = intProp("Combined bytes.")
	case "recall_search":
		props["recall_endpoint"] = stringProp("Configured RecallDock endpoint.")
		props["recall_kind"] = stringProp("Search kind used.")
		props["query"] = stringProp("Search query.")
		props["results"] = arrayProp("Search results.")
		props["candidate_paths"] = arrayProp("Candidate note paths when kind=note.")
		props["candidates"] = arrayProp("Scored candidate notes when kind=note.")
		props["search_result_count"] = intProp("Raw result count before compaction when kind=note.")
		props["search_results"] = arrayProp("Raw search results when requested.")
		props["count"] = intProp("Search result count.")
	case "recall_read":
		props["recall_endpoint"] = stringProp("Configured RecallDock endpoint.")
		props["recall"] = objectProp("RecallDock document returned by the backing service. Raw Markdown is omitted by default and returned as raw_content only when include_raw=true.")
	case "recall_write":
		props["recall_endpoint"] = stringProp("Configured RecallDock endpoint.")
		props["recall_target"] = stringProp("Recall target used.")
		props["recall_action"] = stringProp("Recall action used.")
		props["recall"] = objectProp("RecallDock document returned by the backing service when a write occurs.")
		props["card"] = objectProp("Normalized card candidate or written card when target=card.")
		props["warnings"] = arrayProp("Review warnings before writing.")
		props["capture_plan"] = objectProp("Reviewable write plan for card or note captures.")
		props["similar_results"] = arrayProp("Similar existing card search results.")
		props["path"] = stringProp("RecallDock-relative path.")
		props["changed"] = boolProp("Whether the proposed edit changes content.")
		props["dry_run"] = boolProp("Whether the operation only previewed changes.")
		props["confirmed"] = boolProp("Whether write confirmation was supplied.")
		props["written"] = boolProp("Whether the entry was written.")
		props["diff"] = stringProp("Unified diff preview.")
		props["updates"] = arrayProp("Fact update results.")
	case "recall_maintain":
		props["recall_endpoint"] = stringProp("Configured RecallDock endpoint.")
		props["recall_action"] = stringProp("Maintenance action performed.")
		props["entries"] = arrayProp("RecallDock entries for action=list.")
		props["count"] = intProp("Entry count where applicable.")
		props["terms"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		props["files_scanned"] = intProp("Files scanned for action=lint.")
		props["finding_count"] = intProp("Finding count for action=lint.")
		props["findings"] = arrayProp("Lint findings.")
		props["git_repo"] = boolProp("Whether the RecallDock store is a Git repository for action=sync_status.")
		props["auto_sync_enabled"] = boolProp("Whether RecallDock auto sync is enabled.")
		props["pending_push"] = boolProp("Whether RecallDock has remote sync work.")
		props["conflict"] = boolProp("Whether RecallDock detected a sync conflict.")
	case "private_notes_search":
		props["root"] = stringProp("Private notes root path.")
		props["query"] = stringProp("Search query.")
		props["results"] = arrayProp("Search results with redacted snippets.")
		props["count"] = intProp("Result count.")
		props["redacted"] = boolProp("Whether snippets were redacted.")
	case "private_notes_read":
		props["root"] = stringProp("Private notes root path.")
		props["path"] = stringProp("Plain note path.")
		props["encrypted_path"] = stringProp("Age encrypted backup path, typically encrypted/<category>/<name>.md.age.")
		props["content"] = stringProp("Plaintext content.")
		props["truncated"] = boolProp("Whether content was truncated.")
	case "private_notes_write":
		props["root"] = stringProp("Private notes root path.")
		props["path"] = stringProp("Plain note path.")
		props["encrypted_path"] = stringProp("Age encrypted backup path, typically encrypted/<category>/<name>.md.age.")
		props["written"] = boolProp("Whether plaintext was written.")
		props["encrypted"] = boolProp("Whether encrypted backup was written.")
		props["algorithm"] = stringProp("Encryption algorithm.")
	case "private_notes_maintain":
		props["root"] = stringProp("Private notes root path.")
		props["action"] = stringProp("Action performed.")
		props["notes"] = arrayProp("Private note summaries.")
		props["count"] = intProp("Note count.")
		props["encrypted_count"] = intProp("Encrypted backup count.")
		props["legacy_removed_count"] = intProp("Removed legacy backup count.")
		props["recipient"] = stringProp("Age public recipient generated or used.")
		props["algorithm"] = stringProp("Encryption algorithm.")
		props["missing_encrypted"] = arrayProp("Missing encrypted backup paths.")
	case "browser_session":
		props["operation"] = stringProp("Browser operation name.")
		props["session_id"] = stringProp("Browser session id.")
		props["status"] = stringProp("Browser session status.")
		props["profile_id"] = stringProp("Persistent browser profile id when a session uses profile_id.")
		props["removed_count"] = intProp("Number of stale browser sessions removed by cleanup.")
		props["removed_sessions"] = arrayProp("Browser session ids removed by cleanup.")
		props["stdout"] = stringProp("Raw browser runner output.")
	case "browser_act", "browser_snapshot":
		props["operation"] = stringProp("Browser operation name.")
		props["session_id"] = stringProp("Browser session id.")
		props["url"] = stringProp("Current page URL.")
		props["title"] = stringProp("Current page title.")
		props["text"] = stringProp("Current page body text excerpt.")
		props["screenshot_path"] = stringProp("Saved screenshot path.")
		props["screenshot_file"] = stringProp("Saved screenshot file name.")
		props["screenshot_url"] = stringProp("Artifact URL for the screenshot, when configured.")
		props["screenshot_artifact_id"] = stringProp("Screenshot artifact id.")
		props["artifact"] = objectProp("Structured screenshot artifact metadata.")
		props["viewport"] = objectProp("Browser viewport size.")
		props["page_size"] = objectProp("Page scroll size and device pixel ratio.")
		props["focused_element"] = objectProp("Current focused element summary.")
		props["interactive_elements"] = arrayProp("Visible interactive elements summary.")
		props["screenshot_size_bytes"] = intProp("Screenshot file size in bytes.")
		props["screenshot_width"] = intProp("Estimated screenshot width.")
		props["screenshot_height"] = intProp("Estimated screenshot height.")
		props["image_attached"] = boolProp("Whether screenshot image content is attached.")
		props["image_base64"] = stringProp("Base64 PNG image data when image_attached is true.")
		props["image_mime_type"] = stringProp("Image MIME type when image_attached is true.")
		props["image_size_bytes"] = intProp("Inline image bytes when image_attached is true.")
		props["image_warnings"] = arrayProp("Warnings produced while attaching image content.")
		props["closed"] = boolProp("Whether the session was closed by close_after.")
		props["storage_state_path"] = stringProp("Saved Playwright storage state path when requested.")
		props["console_errors"] = arrayProp("Browser console errors captured during the operation.")
		props["network_errors"] = arrayProp("Network request failures captured during the operation.")
		props["page_errors"] = arrayProp("Browser page runtime errors captured during the operation.")
		props["stdout"] = stringProp("Raw browser runner output.")
		props["truncated"] = boolProp("Whether output was truncated.")
	case "git_read":
		props["action"] = stringProp("Read action performed.")
		props["command"] = stringProp("Executed git command.")
		props["output"] = stringProp("Raw git output.")
		props["repo_path"] = stringProp("Repository path, when applicable.")
		props["repos"] = arrayProp("Repositories for action=repos.")
		props["count"] = intProp("Repository count for action=repos.")
		props["branch"] = stringProp("Branch status line.")
		props["upstream"] = stringProp("Upstream branch, when configured.")
		props["ahead"] = intProp("Commits ahead of upstream.")
		props["behind"] = intProp("Commits behind upstream.")
		props["files"] = arrayProp("Changed files or diff files.")
		props["clean"] = boolProp("Whether the worktree is clean.")
		props["commits"] = arrayProp("Parsed commits for action=log.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["diagnostic"] = objectProp("Structured diagnostic.")
	case "git_write":
		props["action"] = stringProp("Write action performed.")
		props["command"] = stringProp("Executed git command.")
		props["output"] = stringProp("Raw git output.")
		props["repo_path"] = stringProp("Repository path, when applicable.")
		props["dest"] = stringProp("Clone destination, when applicable.")
		props["truncated"] = boolProp("Whether output was truncated.")
		props["diagnostic"] = objectProp("Structured diagnostic.")
		props["push_succeeded"] = boolProp("Whether push exited successfully.")
		props["pushed"] = boolProp("Alias for push_succeeded.")
		props["remote_updated"] = boolProp("Whether push changed remote refs.")
		props["up_to_date"] = boolProp("Whether push reported up-to-date.")
		props["warnings"] = arrayProp("Git warning lines.")
		props["fatal_but_non_blocking"] = boolProp("Whether fatal text was non-blocking.")
		props["push_status"] = stringProp("Structured push status.")

	case "desktop_observe":
		props["operation"] = stringProp("Underlying desktop observation operation.")
		props["app"] = stringProp("Requested app, when applicable.")
		props["running"] = arrayProp("Running visible applications.")
		props["recent"] = arrayProp("Best-effort recently used applications from Spotlight metadata.")
		props["count"] = intProp("Running application count or result count.")
		props["resolved_app"] = stringProp("Resolved running app name.")
		props["bundle_id"] = stringProp("App bundle identifier when available.")
		props["pid"] = intProp("Process id when available.")
		props["frontmost"] = boolProp("Whether the app is frontmost.")
		props["window"] = objectProp("Key window metadata.")
		props["windows"] = arrayProp("Visible windows.")
		props["accessibility_ok"] = boolProp("Whether accessibility tree capture succeeded.")
		props["accessibility_tree"] = arrayProp("Accessibility tree nodes with element indexes.")
		props["node_count"] = intProp("Accessibility tree node count.")
		props["coordinate_space"] = objectProp("Coordinate space metadata for screenshots and actions.")
		props["screenshot_path"] = stringProp("Saved screenshot path.")
		props["screenshot_url"] = stringProp("Artifact URL for the screenshot, when configured.")
		props["screenshot_artifact_id"] = stringProp("Screenshot artifact id.")
		props["mime_type"] = stringProp("Screenshot MIME type.")
		props["width"] = intProp("Screenshot width.")
		props["height"] = intProp("Screenshot height.")
		props["size_bytes"] = intProp("Screenshot size in bytes.")
		props["image_attached"] = boolProp("Whether an MCP image content part is attached.")
	case "desktop_act", "desktop_clipboard":
		props["operation"] = stringProp("Underlying desktop action operation.")
		props["command_ok"] = boolProp("Whether the underlying command exited successfully.")
		props["effect_verified"] = boolProp("Whether UI effect verification was attempted.")
		props["effect_changed"] = boolProp("Whether before/after screenshots changed enough to indicate effect.")
		props["diff_score"] = floatProp("Screenshot difference score when verify=true.")
		props["text"] = stringProp("Clipboard text or typed text, when applicable.")
		props["verified"] = boolProp("Whether clipboard write verification passed, when applicable.")
		props["waited_ms"] = intProp("Wait duration for wait action.")
	case "view_image":
		props["path"] = stringProp("Workspace-relative image path.")
		props["mime_type"] = stringProp("Returned image MIME type.")
		props["width"] = intProp("Returned image width.")
		props["height"] = intProp("Returned image height.")
		props["size_bytes"] = intProp("Returned image size in bytes after optional crop/resize/compression.")
		props["original"] = objectProp("Original/crop metadata.")
		props["resized"] = boolProp("Whether image bytes changed due to crop/resize/re-encode.")
		props["warnings"] = map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
		props["image_attached"] = boolProp("Whether MCP image content is attached.")
		props["data_base64"] = stringProp("Base64-encoded image data when returned.")
		props["data_url"] = stringProp("Data URL when output=data_url.")
	}

	return map[string]any{"type": "object", "properties": props, "required": required, "additionalProperties": true}
}
