#!/usr/bin/env sh
# Install browser-runner and prepare a desktop-like Chromium/Chrome environment for Goal Mode.
# This does not ship Chromium binaries in-repo (size/license); it configures paths so AgentDock
# can use system Chrome/Chromium or a Playwright-managed browser.
set -eu

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
AGENTDOCK_HOME_DIR="${AGENTDOCK_HOME:-$HOME/.agentdock}"
RUNNER_DIR="${AGENTDOCK_BROWSER_RUNNER_DIR:-$AGENTDOCK_HOME_DIR/browser-runner}"
PROFILE_ROOT="$AGENTDOCK_HOME_DIR/browser/profiles"

echo "==> Installing browser runner into $RUNNER_DIR"
mkdir -p "$RUNNER_DIR" "$PROFILE_ROOT/chatgpt" "$PROFILE_ROOT/testing" "$AGENTDOCK_HOME_DIR/browser/screenshots"
cp -R "$ROOT/examples/browser-runner/." "$RUNNER_DIR/"
cd "$RUNNER_DIR"
if command -v npm >/dev/null 2>&1; then
  npm install
else
  echo "npm not found; copy runner sources only. Install Node.js to use browser tools." >&2
fi

# Prefer system Chrome/Chromium when present.
detect_browser() {
  for candidate in \
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
    "/Applications/Chromium.app/Contents/MacOS/Chromium" \
    "$(command -v google-chrome 2>/dev/null || true)" \
    "$(command -v google-chrome-stable 2>/dev/null || true)" \
    "$(command -v chromium 2>/dev/null || true)" \
    "$(command -v chromium-browser 2>/dev/null || true)"
  do
    if [ -n "$candidate" ] && [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

ENV_FILE="$AGENTDOCK_HOME_DIR/browser/env.sh"
{
  echo "# Generated by scripts/bundle-browser-desktop.sh"
  echo "export AGENTDOCK_BROWSER_RUNNER_DIR=\"$RUNNER_DIR\""
  echo "export AGENTDOCK_BROWSER_ENABLED=true"
  if BROWSER_BIN="$(detect_browser)"; then
    echo "export AGENTDOCK_BROWSER_EXECUTABLE_PATH=\"$BROWSER_BIN\""
    echo "Detected browser: $BROWSER_BIN" >&2
  else
    echo "# No system Chrome/Chromium found. Playwright may download browsers on first use,"
    echo "# or set AGENTDOCK_BROWSER_EXECUTABLE_PATH manually."
    echo "No system Chrome/Chromium detected." >&2
  fi
} >"$ENV_FILE"

# shellcheck disable=SC1090
# Users can: source ~/.agentdock/browser/env.sh
printf 'Wrote %s\n' "$ENV_FILE"
printf 'Profiles: %s\n' "$PROFILE_ROOT"
printf 'Next:\n'
printf '  source %s\n' "$ENV_FILE"
printf '  go run ./cmd/agentdock-desktop\n'
printf '  # first ChatGPT login: open dedicated profile and complete CAPTCHA/2FA manually\n'
